### ISSUE TITLE
[Announcements] Code release

### ISSUE THREAD

**Issue by sarlinpe** [cvg/pixloc#1]
Add subscribe to this issue if you wish to be notified of the code release. Please do not contact us to ask for early-access to the code.

**Comment by moneer88** [comment]
Subscribe

**Comment by nosy-b** [comment]
subscribe :)

**Comment by panshaohua** [comment]
Subscribe

**Comment by derbysolto** [comment]
Subscribe

**Comment by HongShiKuan** [comment]
Subscribe

**Comment by antabangun** [comment]
Subscribe

**Comment by hiyyg** [comment]
Subscribe

**Comment by soeroesg** [comment]
people, please press the Subscribe button on the right instead of spamming this thread. thx.

**Comment by Sirius-zn** [comment]
Subscribe

**Comment by ruggeropintus** [comment]
Subscribe

**Comment by JoaoProductDev** [comment]
Subscribe

**Comment by Y980401** [comment]
Subscribe

**Comment by libingan** [comment]
Subscribe

**Comment by Saixiaoma** [comment]
Subscribe

**Comment by 2chae0** [comment]
Subscribe

**Comment by district10** [comment]
> Add subscribe to this issue if you wish to be notified of the code release. Please do not contact us to ask for early-access to the code.

How to subscribe? ⬇⬇⬇⬇

![image](https://user-images.githubusercontent.com/5262037/118105818-75469080-b40f-11eb-8269-5853139590c8.png)

Too many meaningless notifications from this thread. :disappointed:

**Comment by alighofrani95** [comment]
Dear Sarlin,
We still wait to release the code ...

**Comment by Eunju-Jeong178** [comment]
Subscribe :)

**Comment by Skydes** [comment]
Quick update: we will release the code in the very next days! In the meantime, you can:
- check out the cool visualizations on the new project page: https://psarlin.com/pixloc/ All of those will be included in the release!
- watch the 5-minute video: https://www.youtube.com/watch?v=vPkXhKQn2oI

Stay tuned 🙂

**Comment by Kanishk598** [comment]
Subscribe!
I am working on a very relevant project involving drones in stadiums, and this seems one of the best methods for localization out there.

**Comment by CGCooke** [comment]
Subscribe!
Awesome work!

**Comment by sam1am** [comment]
What happened? Is code still coming?

**Comment by Skydes** [comment]
The summer break got in the way so we had to delay the release. We're aiming for ~1-2 weeks from now!

**Comment by ravi-aicradle** [comment]
Subscribe

**Comment by TBetterman** [comment]
subscribe, cool!

**Comment by hiyyg** [comment]
> The summer break got in the way so we had to delay the release. We're aiming for ~1-2 weeks from now!

3 weeks past.

**Comment by WellYoungIOE** [comment]
> The summer break got in the way so we had to delay the release. We're aiming for ~1-2 weeks from now!

3 weeks passed.

**Comment by AIBluefisher** [comment]
3 weeks passed.

**Comment by ThorJonsson** [comment]
Can't wait!

**Comment by cuhkjpan** [comment]
Great work, subscribe!

**Comment by hmf17** [comment]
subscribe

**Comment by GeTRight911** [comment]
subscribe！！！！

**Comment by TahaK** [comment]
Great work, subscribe!

**Comment by angiend** [comment]
Great work, can't wait.

**Comment by Stocastico** [comment]
> Quick update: we will release the code in the very next days! In the meantime, you can:
> 
>     * check out the cool visualizations on the new project page: https://psarlin.com/pixloc/ All of those will be included in the release!
> 
>     * watch the 5-minute video: https://www.youtube.com/watch?v=vPkXhKQn2oI
> 
> 
> Stay tuned 🙂

Any updates? It's been 3 months since this announcement...

**Comment by ssssjiang** [comment]
3 months passed.😢

**Comment by JohnHardline** [comment]
> 
> 
> I think we are all eagerly awaiting the code, however there is nothing stopping us writing our own implementation, if we so wish. I'm sure that @Skydes will release it as soon as he can, but I don't think it's fair to call his motivations into question.

Sure, I'm also very grateful for all the paper with codes - however, if someone promises to release the code in the paper - releasing the code is not optional or a generous gift to the community since you have an advantage over papers without codes in the review process. This is especially true for CVPR papers, which is a very competitive conference!

**Comment by WXONE** [comment]
Subscribe

**Comment by zsz00** [comment]
Any updates? It's been 7 months since this announcement...

**Comment by JohnHardline** [comment]
Of course the plain link is not in the submitted paper. However, the sentence is surely in the submitted paper! 
Care to comment @Skydes !
