### ISSUE TITLE
RuntimeError:Function 'PowBackward1' returned nan values in its 0th output

### ISSUE THREAD

**Issue by angiend** [cvg/pixloc#16]
when i retrain the CMU datasets, and get an error like below,  

[log.txt](https://github.com/cvg/pixloc/files/7553372/log.txt)

![11](https://user-images.githubusercontent.com/39428557/142172576-32c7ab81-d2d4-488d-88ea-46fa6a200fa4.png)

**Comment by Skydes** [comment]
Let's discuss this issue in https://github.com/cvg/pixloc/issues/10.
