### ISSUE TITLE
got an ffmpeg error

### ISSUE THREAD

**Issue by Ma-yiwei** [cvg/pixloc#17]
I got an error when run the demo.ipynb:

`Error: ffmpeg error (see stderr output for detail)`

I don't know if I use the wrong version of ffmpeg because there is no detailed version information about it. So, can you share with me the version? or do you have any advice about this error?

**Comment by Skydes** [comment]
Where does the crash occur? The full error traceback might not appear in the notebook but rather in the console from which Jupyter was launched. Make sure that you installed the `ffmpeg-python` package: https://github.com/kkroening/ffmpeg-python You also need a working ffmpeg installation, on my machine I have `version 3.4.8-0ubuntu0.2`.

**Comment by Ma-yiwei** [comment]
Thanks a lot, I have already solved this error by inputting the ffmpeg command directly.
