### ISSUE TITLE
How the intrinsic values are calculated for Cambridge and 7 Scenes dataset?

### ISSUE THREAD

**Issue by patelajaychh** [cvg/pixloc#19]
Intrinsic parameters for query images in Cambridge and 7Scenes dataset are not available. But PixLoc requires calibrated query images so how these parameters are calculated to evaluating on these datasets?

Thanks!

**Comment by Skydes** [comment]
The intrinsics are actually available. They are estimated from SfM as part of the ground truthing process. Here we simply extract them from the GT SfM models using hloc: https://github.com/cvg/Hierarchical-Localization/blob/master/hloc/pipelines/Cambridge/utils.py#L42 The GT SfM models were kindly provided by the authors of the recent [ICCV 2021 paper *On the Limits of Pseudo Ground Truth in Visual Camera Re-localisation*](https://openaccess.thecvf.com/content/ICCV2021/papers/Brachmann_On_the_Limits_of_Pseudo_Ground_Truth_in_Visual_Camera_ICCV_2021_paper.pdf).

**Comment by patelajaychh** [comment]
Thanks!
Can you please also provide GT poses for Cambridge and 7Scenes used for evaluating PixLoc paper.

**Comment by Skydes** [comment]
The COLMAP models containing the GT query poses can be downloaded with our download.py script or with [the commands linked above](https://github.com/cvg/Hierarchical-Localization/tree/master/hloc/pipelines/Cambridge#installation): 

Cambridge: https://drive.google.com/file/d/1esqzZ1zEQlzZVic-H32V6kkZvc4NeS15/view
7Scenes: https://drive.google.com/file/d/1cu6KUR7WHO7G4EO49Qi3HEKU6n_yYDjb/view

**Comment by patelajaychh** [comment]
I'm running SFM reconstruction of Cambridge KingsCollege scene using  command- 
`colmap mapper --database_path /data/hloc/outputs_KingsCollege/sfm_superpoint+superglue/database.db --image_path /data/datasets/Cambridge/KingsCollege/images_all --output_path /data/hloc/outputs_KingsCollege/sfm_superpoint+superglue/models --Mapper.num_threads 16` 

There are total 1565 images. Its already 8hr and its still running. Is this usual? Also process is not using GPU. Does `mapper` function in COLMAP not support GPU? 


I'm wondering how much time did it take to create above shared ground truths? Is it possible to share time profile of each scene?
