### ISSUE TITLE
What is Oracle referred in Pixloc paper?

### ISSUE THREAD

**Issue by patelajaychh** [cvg/pixloc#22]
PixLoc, trained on MegaDepth, is initialized with image retrieval obtained with either DenseVLAD [88] or an `oracle`, which returns the reference image containing the largest number of inlier matches found by hloc. This `oracle` shows the benefits of better image retrieval using a more complex pipeline without ground truth information.

**Comment by tsattler** [comment]
Doesn't the passage that you quote answer your question?

**Comment by Skydes** [comment]
The oracle can be enabled by adding the flag `refinement.do_inlier_ranking=true` to the command line: https://github.com/cvg/pixloc/blob/master/pixloc/localization/refiners.py#L61
