### ISSUE TITLE
'CambridgeLandmarks_Colmap_Retriangulated_1024px.zip' this file can't be downloaded 

### ISSUE THREAD

**Issue by juju904** [cvg/pixloc#34]
Hi,
I'm trying to download 'CambridgeLandmarks_Colmap_Retriangulated_1024px.zip',but  this file can't be downloaded .I don't know why.Do you know why ?

**Comment by Skydes** [comment]
It seems that the downloader is now broken for files hosted on Google Drive. I suspect that they changed their query API (cliget is also broken on my end). You can instead download the file manually from the link https://drive.google.com/file/d/1esqzZ1zEQlzZVic-H32V6kkZvc4NeS15/view

**Comment by tsattler** [comment]
Also, there is a limit on how often a file can be downloaded from a Google Drive folder each day.

**Comment by juju904** [comment]
Thank you very much. 
With your help, I have successfully downloaded it now!
