### ISSUE TITLE
ImportError: cannot import name 'set_logging_debug'

### ISSUE THREAD

**Issue by wwtx9** [cvg/pixloc#35]
Hi, Thanks a lot for releasing your project. This is very amazing work. I meet a problem when I try to run code with run_CMU.py. it shows that ImportError: cannot import name 'set_logging_debug'. and also I didn't find logger in the directory where include run_CMU.py. could you help me with how to fix this? Thanks a lot.

**Comment by Skydes** [comment]
The logging functions are defined here:
https://github.com/cvg/pixloc/blob/0072dc75e2e64b6a77dc7e92f07ac008d9875812/pixloc/__init__.py#L1-L18
which is imported by `run_CMU.py`:
https://github.com/cvg/pixloc/blob/0072dc75e2e64b6a77dc7e92f07ac008d9875812/pixloc/run_CMU.py#L3
So it's unclear why the import would fail.

**Comment by wwtx9** [comment]
@Skydes Thanks for your reply. I figured it out. But when I have tried the following command:
```python -m pixloc.download --select CMU --CMU_slices 9 --training```
```python -m pixloc.pixlib.train pixloc_cmu_train  --conf pixloc/pixlib/configs/train_pixloc_cmu.yaml data.train_slices=[9] data.val_slices=[9]'''
it shows that AttributeError: 'ArgumentParser' object has no attribute 'parse_intermixed_args'. btw, my python is 3.6.13.

**Comment by Skydes** [comment]
It seems that `parse_intermixed_args` was added only in Python 3.7 but we actually don't really need it. Can you please let me know if PR https://github.com/cvg/pixloc/pull/36 works for you?

**Comment by wwtx9** [comment]
Hi, @Skydes thank you for your reply. parse_args works well on my side. But I cannot train successfully on my single Nvidia 1080. Is your minimum memory requirement for the graphics card 11GB？thank you again.

**Comment by Skydes** [comment]
Yes we ran all experiments on a 11GB 1080 Ti.

**Comment by wwtx9** [comment]
@Skydes thank you very much!
