### ISSUE TITLE
Using sfm model on 7scenes without depth

### ISSUE THREAD

**Issue by MisEty** [cvg/pixloc#38]
Hi, Thanks for your sharing work. I noticed that the demo on 7scenes need the reference_sfm model "sfm_superpoint+superglue+depth". But I cannot download the rendered 7scenes depth images and only have the sfm model builded from RGB images. Can I use such reference sfm model directly on the pre-trained model?

**Comment by sarlinpe** [comment]
Yes definitely, but the results will not be as accuracy as with depth. Why can't you download the depth images though? We used the renderings available [here](https://heidata.uni-heidelberg.de/api/access/datafile/4037). The pipeline is implemented [here](https://github.com/cvg/Hierarchical-Localization/tree/master/hloc/pipelines/7Scenes).

**Comment by MisEty** [comment]
I can download the rendered 7scenes depth images today. Maybe just some network failures and I will try sfm model with depth again.
Thanks!
