### ISSUE TITLE
About colmap's scale proplem

### ISSUE THREAD

**Issue by BoMingZhao** [cvg/pixloc#47]
Hi, thanks for you amazing work!! 
I saw that when using the Cambridge dataset, the camera pose and point cloud are obtained from colmap, while the cambridge dataset was originally obtained from visualSFM. I compared the two files and found that the camera pose is not consistent. 
Whether there will be a scale that will lead to inaccurate evaluation results?

**Comment by tsattler** [comment]
Can you share statistics of the camera position errors? Do you take into account that Colmap stores translations while VSFM stores camera center positions?

**Comment by BoMingZhao** [comment]
> Can you share statistics of the camera position errors? Do you take into account that Colmap stores translations while VSFM stores camera center positions?

Thank you very much for your reply! I didn't consider it.
