### ISSUE TITLE
Checkpoint and dataset issue

### ISSUE THREAD

**Issue by twdent** [cvg/pixloc#48]
Hi, thanks for the awesome work!
When trying to run pixloc.download as described in the readme, I get teh following error:
subprocess.CalledProcessError: Command 'wget -r -np -nH -q --show-progress -R "index.html*" --cut-dirs 2 https://cvg-data.inf.ethz.ch/pixloc_CVPR2021/checkpoints/ -P C:{user}\pixloc\outputs\training -nc' returned non-zero exit status 1.

I seem to be able to access the files in a browser. 
Thanks in advance for any insights

**Comment by flybiubiu** [comment]
+1

**Comment by sarlinpe** [comment]
Does the command run if pasted in the terminal?
