### ISSUE TITLE
how to get the extrinsics between the cameras

### ISSUE THREAD

**Issue by angiend** [cvg/pixloc#7]
thanks  for your great work.
i have download the robotcar from the url, and run the code "run_RobotCar.py" and get the result like this,

_left/1418235223450115.jpg 0.11704475375741745 0.03295656318232015 -0.6387011805495836 -0.759786280822208 -125.37236785888672 -23.192873001098633 -7.491024494171143
rear/1418235392061935.jpg 0.7276782815863018 -0.5911740329291926 -0.23252374914543117 -0.2587088853928167 -100.58859252929688 -41.86554718017578 207.1205291748047
right/1418236138953803.jpg 0.6205097424969388 -0.6552427198975653 -0.20077227393455488 -0.3812022186540521 24.56517219543457 7.398570537567139 -221.69622802734375_

**i would like to know how to get the extrinsics between the cameras?**

**Comment by Skydes** [comment]
The format of the text file is:
```
image_name qw qx qy qz tx ty tz
```
The pose is expressed as quaternion `qw qx qy qz` and camera translation `tx ty tz` in the COLMAP coordinate system, i.e. from the world to camera frame.

**Comment by Skydes** [comment]
Sorry for the late reply. The extrinsics between left and right cameras are not publicly available for RobotCar, but you can estimate them using rotation averaging on the reference poses.

**Comment by tsattler** [comment]
The extrinsics for the cameras with respect to the car are actually available together with the RobotCar Seasons dataset. From this, you can compute the relative poses between the left and right camera.

**Comment by angiend** [comment]
thank you very much. @Skydes @tsattler
